### PR TITLE
fix: update pnpm lock

### PR DESCRIPTION
**Pull request by elonehoo**

### CODE REVIEW

**Comment by elonehoo** [comment]
image
出现了这个错误，我却没有办法找到原因...

**Comment by elonehoo** [comment]
> image 出现了这个错误，我却没有办法找到原因...

[421d668](https://github.com/vitest-dev/docs-cn/pull/120/commits/421d668c7ca8e8fd8bf33391df67e7a656f7cf31)我在这里已经提升了版本，但是还是有这个问题，难道真的是 unplugin-vue-components 的错误？

**Comment by watonyweng** [comment]
@elonehoo [unplugin-vue-components#484](https://github.com/antfu/unplugin-vue-components/issues/484)

**Comment by elonehoo** [comment]
啊这

**Comment by watonyweng** [comment]
add `"type": "module"` to package.json or upgrade to `0.22.3`

**Comment by elonehoo** [comment]
我等一下尝试一下，我的电脑老出问题

**Comment by watonyweng** [comment]
Hi @elonehoo, I checked the [ci](https://github.com/vitest-dev/docs-cn/pull/120/checks?check_run_id=7742673922) and confirmed that `pathe` is missing, which can be found [here](https://github.com/vitest-dev/vitest/blob/main/scripts/update-examples.ts#L3-L12).

**Comment by watonyweng** [comment]
@elonehoo @amadeus711 我今天试出来了，目前的方案是锁定 `vite-plugin-pwa` 的版本为 `0.12.2`，`0.12.3`的版本会报 [jest-worker](https://app.netlify.com/sites/cn-vitest/deploys/62f66c5ba9663a000d040158) 这个错误。

**Pull request merged**
